### PR TITLE
Layout route ethernet

### LINKED ISSUE #26: Create Kicad layout V1 design based on schematic
Based on schematic https://github.com/openeew/openeew-sensor/issues/25

Using Arrow components where possible to allow us to make the boards at a discounted price.

Use SMT components that a MC-385V2V PnP can use : 0201 components to 100x150mm components

### PR DESCRIPTION
**Pull request by perigoso**
Routed the ethernet circuit.

image

### CODE REVIEW

**Comment by perigoso** [comment]
Merge if ok

**Comment by andygrillo** [comment]
hey @perigoso , the layout is much cleaner than before. Given that the previous ethernet layout worked (well...apart from the wrong pin connections), have you made any significant changes eg trace widths?

for reference here is the older design (how did you manage to find so much space!?) :
Capture

**Comment by perigoso** [comment]
The only major difference between this and the original, apart from the layout, is the components sizes, I went down a size on most, to 0402, but that shouldn't affect function

**Comment by perigoso** [comment]
Most traces are routed with 0.25mm

**Comment by andygrillo** [comment]
ok. Seems fine to me.

**Pull request merged**
