### PR TITLE
PCB Ported to KiCad

### PR DESCRIPTION
**Pull request by perigoso**
Porting of the hardware files to KiCad.

### CODE REVIEW

**Review by andygrillo — APPROVED** [review]

**Comment by andygrillo** [comment]
looks good @gimbas .  This is a draft PR so I can't merge.

**Comment by perigoso** [comment]
Yes, I know, the merge is not ready yet.

**Comment by perigoso** [comment]
Schematic with the original connections for continuity sake.
Layout was not replicated because i feel the time investment was not worth it, since it will be modified in the upcoming revisions, the original outline was copied and so was the location of the main components.

For reference and review:

[layout](https://user-images.githubusercontent.com/39195157/90192328-a7f92500-ddba-11ea-8f98-11d1f740b2b3.png)
[schematic.pdf](https://github.com/openeew/openeew-sensor/files/5071714/schematic.pdf)

**Comment by perigoso** [comment]
Ups, outdated schematic.

There are some discrepancies between the uploaded files and the pdf I submitted to aid review, nothing too important changed though.

**Comment by andygrillo** [comment]
I did my best to compare your schematic with the eagle schematic. Seems right to me.

**Comment by andygrillo** [comment]
layout is much neater

**Comment by andygrillo** [comment]
You used the ESP32 Wroom right ?

**Pull request merged**
