### PR TITLE
Placement on KiCad v5.99 (next step on #5)

### PR DESCRIPTION
**Pull request by hildogjr**
Made almost the complet placement on KiCad (missing some decopling capacitors)
Improved some track (supply track MUST go to decopling capacitors and after to IC)
Small improvements
Missing buffer footprint from #5

### CODE REVIEW

**Comment by perigoso** [comment]
Why did you opt with KiCad nightly? We were currently using the Latest Stable version

**Comment by perigoso** [comment]
Also, if we were to upgrade to this version of KiCad we should not keep track of `pcb.kicad_prl` since it's a `Project local settings file`

**Comment by hildogjr** [comment]
I help the developers, testing, fixing and proposing new features.

Usually I have just the Nightly installed. Because I just have academic / open projects (and also knowledge of the saved file architecture), use the Nightly was never an issue for me.

**Comment by perigoso** [comment]
I also personally use nightly regularly and in my experience it is very stable, but even so I think it is best to keep with the latest stable release, when version 6 is released we can upgrade.

**Comment by perigoso** [comment]
Thank you for helping with the conversion, but I was currently leaving the layout on hold until we had all the schematic corrections and changes for the next revision finished, see #12, this was also mentioned on #5 [here](https://github.com/openeew/openeew-sensor/pull/5#issuecomment-673736850).

It is good practice to contact the people working on a project to make sure your contributions go smoothly, try opening an issue or join the [slack](https://join.slack.com/t/openeew/shared_invite/zt-cibhc0za-XKReMPobi2DsrPusORJZVQ), also when making changes to the hardware, try to describe them well and include screenshots, it is hard to visualize changes from the text on the files.

If you wish to help your best course of action right now would be reviewing the schematics looking for possible problems or oversights or help debug the issues mentioned on #12.

**Comment by perigoso** [comment]
@andygrillo I think you can close this.

**Comment by andygrillo** [comment]
done!

**Pull request merged**
